# Site settings
title: Javier Bullrich
name: Javier Bullrich
presentation:
    email: javier@bullrich.dev
    image: images/bio-javi.jpg
    name: Javier Bullrich
    title: Developer
    address: Innsbruck, Austria

permalink: /portfolio/:title
plugins:
  - jekyll-redirect-from

# Colections settings
collections:
  employment:
  education: